import numpy as np
import torch
import torch.fft as fft
import matplotlib.pyplot as plt


def _angular_spectrum_transfer_function(
    shape: tuple[int, int],
    distance_mm: float,
    wavelength_um: float,
    pixel_pitch_um: float,
    *,
    device: torch.device,
    dtype: torch.dtype,
) -> torch.Tensor:
    if wavelength_um <= 0:
        raise ValueError("wavelength_um must be positive")
    if pixel_pitch_um <= 0:
        raise ValueError("pixel_pitch_um must be positive")

    height, width = shape
    pitch_m = pixel_pitch_um * 1e-6
    wavelength_m = wavelength_um * 1e-6
    distance_m = distance_mm * 1e-3

    fx = fft.fftfreq(width, d=pitch_m, device=device, dtype=dtype)
    fy = fft.fftfreq(height, d=pitch_m, device=device, dtype=dtype)
    fy_grid, fx_grid = torch.meshgrid(fy, fx, indexing="ij")
    longitudinal_frequency_squared = (
        1.0 / wavelength_m**2 - fx_grid**2 - fy_grid**2
    )
    propagating = longitudinal_frequency_squared >= 0
    longitudinal_frequency = torch.sqrt(
        torch.clamp(longitudinal_frequency_squared, min=0)
    )
    phase = 2 * torch.pi * distance_m * longitudinal_frequency
    transfer = torch.exp(1j * phase)
    return torch.where(propagating, transfer, torch.zeros_like(transfer))


def _propagate_with_transfer(
    field: torch.Tensor, transfer: torch.Tensor
) -> torch.Tensor:
    return fft.ifft2(fft.fft2(field) * transfer)


def angular_spectrum_propagate(
    field: torch.Tensor,
    distance_mm: float,
    wavelength_um: float,
    pixel_pitch_um: float,
):
    """Propagate a sampled complex field with the angular-spectrum method.

    Positive ``distance_mm`` propagates from the ideal 4f image plane toward
    the actual objective pupil. Negative distances propagate in the opposite
    direction. The last two tensor dimensions are interpreted as ``(y, x)``.
    """
    if distance_mm == 0:
        return field
    if field.ndim < 2:
        raise ValueError("field must have at least two dimensions")
    transfer = _angular_spectrum_transfer_function(
        tuple(field.shape[-2:]),
        distance_mm,
        wavelength_um,
        pixel_pitch_um,
        device=field.device,
        dtype=field.real.dtype,
    )
    return _propagate_with_transfer(field, transfer)


def circular_pupil_mask(
    shape: tuple[int, int],
    pixel_pitch_um: float,
    pupil_radius_mm: float,
    *,
    device: torch.device,
    dtype: torch.dtype,
) -> torch.Tensor:
    """Return a centered circular objective-pupil mask on an image-plane grid."""
    if pupil_radius_mm <= 0:
        raise ValueError("pupil_radius_mm must be positive")
    height, width = shape
    y = (
        torch.arange(height, device=device, dtype=dtype) - height / 2
    ) * pixel_pitch_um * 1e-3
    x = (
        torch.arange(width, device=device, dtype=dtype) - width / 2
    ) * pixel_pitch_um * 1e-3
    y_grid, x_grid = torch.meshgrid(y, x, indexing="ij")
    return x_grid**2 + y_grid**2 <= pupil_radius_mm**2


def WGS_phase_generate(
    initSLMAmp: torch.Tensor,
    initSLMPhase: torch.Tensor,
    targetAmp: torch.Tensor,
    Loop=5,
    threshold=0.01,
    Plot: bool = False,
    delta_z_mm: float = 0.0,
    wavelength_um: float = 0.795,
    image_pixel_pitch_um: float = 12.5,
    pupil_radius_mm: float | None = None,
):
    '''
    This function uses WGS algorithm to generate hologram according to your input targetAmp.
    
    Parameters
    ----------
    initSLMAmp : 2D_tensor
        The amplitude distrubution of the incident laser, typically gaussian distrubution.
    
    initSLMPhase : 2D_tensor
        The phase distrubution of SLM plane for the initial calculation. If generate a new target, use a random initPhase. 
        If generate a series of dynamic targets, use the phase generated by the last WGS.
        
    targetAmp : 2D_tensor
        The amplitude distrubution of the target. 
        
    Loop :
        The number of iteration loops in WGS calculation, typically 5~20 is enough.
        
    threshold :
        The phase fix threshold in WGS calculation. If the non-uniformity < threshold, the phase in focal plane will be fixed.
        
    Plot : 
        Whether to plot non-uniformity vs iteration. Default to be False.

    delta_z_mm :
        Axial distance from the ideal 4f image plane to the actual objective
        pupil, in mm. Zero preserves the original WGS propagation exactly.

    wavelength_um :
        Vacuum wavelength in um, used by the pupil-conjugation propagation.

    image_pixel_pitch_um :
        Sampling pitch at the ideal 4f image plane in um.

    pupil_radius_mm :
        Radius of the objective entrance pupil in mm. When omitted, no pupil
        clipping is added, preserving legacy behavior for ``delta_z_mm=0``.
        
    '''

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    torch.backends.cudnn.benchmark = True

    initSLMAmp = initSLMAmp.to(device)
    initSLMPhase = initSLMPhase.to(device)
    targetAmp = targetAmp.to(device)

    pupil_mask = None
    if pupil_radius_mm is not None:
        pupil_mask = circular_pupil_mask(
            tuple(initSLMAmp.shape[-2:]),
            image_pixel_pitch_um,
            pupil_radius_mm,
            device=device,
            dtype=initSLMAmp.dtype,
        )

    forward_transfer = None
    if delta_z_mm != 0:
        forward_transfer = _angular_spectrum_transfer_function(
            tuple(initSLMAmp.shape[-2:]),
            delta_z_mm,
            wavelength_um,
            image_pixel_pitch_um,
            device=device,
            dtype=initSLMAmp.dtype,
        )

    SLM_Field = torch.multiply(initSLMAmp, torch.exp(1j*initSLMPhase))
    targetAmp = targetAmp/torch.sqrt(torch.sum(torch.square(targetAmp)))
    targetAmpmask = (targetAmp != 0)*1
    # targetAmpmask = (targetAmp > 0)*1
    totalsites = torch.count_nonzero(targetAmp)
    count = 0
    g_coeff0 = torch.ones(1).to(device)
    Focal_phase = torch.zeros_like(targetAmp).to(device)
    fftAmp = torch.zeros_like(targetAmp).to(device)
    non_uniform = torch.zeros(Loop).to(device)

    targetAmp_weightfactor = torch.abs(targetAmp) / torch.sum(torch.abs(targetAmp))

    while count < Loop:
        if forward_transfer is None:
            pupil_field = SLM_Field
        else:
            pupil_field = _propagate_with_transfer(SLM_Field, forward_transfer)
        if pupil_mask is not None:
            pupil_field = pupil_field * pupil_mask
        fftSLM = fft.fft2(pupil_field)
        fftSLMShift = fft.fftshift(fftSLM)
        fftSLM_norm = torch.sqrt(torch.sum(torch.square(torch.abs(fftSLMShift))))
        fftSLMShift_norm = fftSLMShift / fftSLM_norm

        fftAmp = torch.abs(fftSLMShift_norm)
        fftAmp_foci = torch.multiply(fftAmp, targetAmpmask)

        non_uniform[count] = nonUniformity_adapt(fftAmp_foci, targetAmp, totalsites)

        fftAmp_foci_avg = torch.multiply(torch.sum(fftAmp_foci) / totalsites, targetAmpmask)

        g_coeff = torch.where(fftAmp_foci != 0,
                              torch.multiply(torch.div(torch.multiply(fftAmp_foci_avg, targetAmp_weightfactor), fftAmp_foci),g_coeff0),
                              torch.zeros_like(fftAmp_foci_avg).to(device))
                                                
        Focal_Amp = torch.multiply(targetAmp, g_coeff)

        if non_uniform[count] > threshold or count == 0:
            Focal_phase0 = torch.angle(fftSLMShift_norm)
        else:
            Focal_phase0 = Focal_phase
        # Focal_phase0 = torch.angle(fftSLMShift_norm)
        
        Focal_phase = Focal_phase0
        Focal_Field = torch.multiply(Focal_Amp, torch.exp(1j * Focal_phase))

        image_plane_field = fft.ifft2(fft.ifftshift(Focal_Field))
        if pupil_mask is not None:
            image_plane_field = image_plane_field * pupil_mask
        if forward_transfer is not None:
            image_plane_field = _propagate_with_transfer(
                image_plane_field, torch.conj(forward_transfer)
            )
        SLM_Phase = torch.angle(image_plane_field)

        SLM_Field = torch.multiply(initSLMAmp, torch.exp(1j * SLM_Phase))
        g_coeff0 = g_coeff
        count += 1

    # SLM_Amp = torch.abs(SLM_Field)
    SLM_Phase = torch.angle(SLM_Field)
    
    if Plot:
            plt.plot(non_uniform.cpu())
            plt.grid()
            plt.yscale('log')
            plt.xlabel('Iteration')
            plt.ylabel('Non-uniformity')
            plt.show()

    return SLM_Phase


def WGS3D_phase_generate(initSLMAmp:torch.Tensor, initSLMPhase:torch.Tensor, targetAmp:torch.Tensor, targetLayer:torch.Tensor, Loop = 5, threshold = 0.01, Plot:bool = False):
    '''
    This function uses 3D WGS algorithm to generate hologram according to your input targetAmp.
    
    Parameters
    ----------
    initSLMAmp : 2D_tensor
        The amplitude distrubution of the incident laser, typically gaussian distrubution.
    
    initSLMPhase : 2D_tensor
        The phase distrubution of SLM plane for the initial calculation. If generate a new target, use a random initPhase. 
        If generate a series of dynamic targets, use the phase generated by the last WGS.
        
    targetAmp : 3D_tensor
        Containing multi layers of targetAmp. [targetAmp1, targetAmp2, targetAmp3...]
    
    targetLayer : 1D_tensor
        Representing the position of each target layer relative to the actual focal plane. The unit is um. [z1, z2, z3...]
        
    Loop :
        The number of iteration loops in WGS calculation, typically 5~20 is enough.
        
    threshold :
        The phase fix threshold in WGS calculation. If the non-uniformity < threshold, the phase in focal plane will be fixed.
        
    Plot : 
        Whether to plot non-uniformity vs iteration. Default to be False.
         
    '''

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    torch.backends.cudnn.benchmark = True

    initSLMAmp = initSLMAmp.to(device)
    initSLMPhase = initSLMPhase.to(device)
    targetAmp = targetAmp.to(device)
    
    layer_num = targetLayer.shape[0]

    SLM_Field = torch.multiply(initSLMAmp, torch.exp(1j*initSLMPhase))
    targetAmp = targetAmp/torch.sqrt(torch.sum(torch.square(targetAmp)))
    targetAmpmask = (targetAmp > 0)*1
    totalsites = torch.count_nonzero(targetAmp)

    count = 0
    g_coeff0 = torch.ones(1).to(device)
    Focal_phase = torch.zeros_like(targetAmp).to(device)
    # Note: the dtype of the following two tensors must be specified to torch.complex.
    Propagation_Field = torch.zeros_like(targetAmp, dtype=torch.complex128).to(device)
    Backpropagation_Field = torch.zeros_like(targetAmp, dtype=torch.complex128).to(device)
    non_uniform = torch.zeros(Loop).to(device)

    targetAmp_weightfactor = torch.abs(targetAmp) / torch.sum(torch.abs(targetAmp))

    while count < Loop:
        
        for i in range(layer_num):
            layer = targetLayer[i]
            Propagation_Field[i] = fft.fftshift(fft.fft2( torch.multiply(SLM_Field, torch.exp(-1j*fresnel_lens_phase_generate(layer))) ))
            
        Propagation_Field_norm_coeff = torch.sqrt(torch.sum(torch.square(torch.abs(Propagation_Field))))
        Propagation_Field_norm = Propagation_Field/Propagation_Field_norm_coeff
        
        Propagation_Amp = torch.abs(Propagation_Field_norm)
        Propagation_Amp_foci = torch.multiply(Propagation_Amp, targetAmpmask)

        non_uniform[count] = nonUniformity_adapt(Propagation_Amp_foci, targetAmp, totalsites)
        
        Propagation_Amp_foci_avg = torch.multiply(torch.sum(Propagation_Amp_foci) / totalsites, targetAmpmask)
        g_coeff = torch.where(Propagation_Amp_foci != 0, torch.multiply(torch.div(torch.multiply(Propagation_Amp_foci_avg, targetAmp_weightfactor), Propagation_Amp_foci),g_coeff0), torch.zeros_like(Propagation_Amp_foci_avg).to(device))                                             
        Focal_Amp = torch.multiply(targetAmp, g_coeff)

        if non_uniform[count] > threshold or count == 0:
            Focal_phase0 = torch.angle(Propagation_Field_norm)
        else:
            Focal_phase0 = Focal_phase
        
        Focal_phase = Focal_phase0
        Focal_Field = torch.multiply(Focal_Amp, torch.exp(1j * Focal_phase))
        
        for i in range(layer_num):
            layer = targetLayer[i]
            # Backpropagation_Field[i] = fft.ifft2(fft.ifftshift( torch.multiply(Focal_Field[i], torch.exp(1j*fresnel_lens_phase_generate(layer))) ))
            Backpropagation_Field[i] = torch.multiply(fft.ifft2(fft.ifftshift(Focal_Field[i])), torch.exp(1j*fresnel_lens_phase_generate(layer)))
    
        SLM_Field = Backpropagation_Field.sum(axis=0)
        SLM_Phase = torch.angle(SLM_Field)

        SLM_Field = torch.multiply(initSLMAmp, torch.exp(1j * SLM_Phase))
        g_coeff0 = g_coeff
        count += 1

    # SLM_Amp = torch.abs(SLM_Field)
    SLM_Phase = torch.angle(SLM_Field)
    
    if Plot:
            plt.plot(non_uniform.cpu())
            plt.grid()
            plt.yscale('log')
            plt.xlabel('Iteration')
            plt.ylabel('Non-uniformity')
            plt.show()

    return SLM_Phase


def fresnel_lens_phase_generate(shift_distance, SLMRes=(4096,4096), x0=2048, y0=2048, pixelpitch=17,wavelength=0.813,focallength=4000,magnification=0.375):
        '''
        the fresnel lens phase, see notion for more details.
        '''
        
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        torch.backends.cudnn.benchmark = True

        Xps, Yps = torch.meshgrid(torch.linspace(0, SLMRes[0], SLMRes[0]), torch.linspace(0, SLMRes[1], SLMRes[1]))
        Xps = Xps.to(device)
        Yps = Yps.to(device)

        X = (Xps-x0)*pixelpitch
        Y = (Yps-y0)*pixelpitch

        fresnel_lens_phase = torch.fmod(torch.pi*(X**2+Y**2)*shift_distance/(wavelength*focallength**2)*magnification**2,2*torch.pi)

        return fresnel_lens_phase
    

def nonUniformity_adapt(Amp_foci, targetAmp_adapt, totalsites):
    '''
    This function calculates the nonUniformity with the non-uniform targetAmp distribution.
    Amp_foci is the field amplitude at the focal plane. It is a tensor.
    targetAmp_adapt is the non-uniform targetAmp distribution.
    '''
    Inten_foci = torch.square(Amp_foci) / torch.sum(torch.square(Amp_foci))
    Inten_foci_nonzero = torch.abs(Inten_foci[Inten_foci != 0])
    Inten_adapt = torch.square(targetAmp_adapt) / torch.sum(torch.square(targetAmp_adapt))
    Inten_adapt_nonzero = torch.abs(Inten_adapt[Inten_adapt != 0])
    non_Uniform = torch.sqrt(torch.sum(torch.square(Inten_foci_nonzero - Inten_adapt_nonzero))) / totalsites / torch.mean(Inten_adapt_nonzero)
    
    return non_Uniform


def phase_to_screen(SLM_Phase):
    '''
    This function converts the SLM_Phase calculated by WGS to  fit to the SLM screen.
    Temporarily for 4096*4096 phase to 1024*1272 screen.
    '''
    SLM_IMG = SLM_Phase[1536:2560, 1536:2560]
    SLM_bit = np.around((SLM_IMG+np.pi)/(2*np.pi)*256).astype('uint8')
    
    return SLM_bit


def phase_to_screen_cuda(SLM_Phase):
    device = "cuda"
    SLM_Phase = SLM_Phase.to(device)
    SLM_IMG = SLM_Phase[1536:2560, 1536:2560]
    SLM_bit = torch.round((SLM_IMG + torch.pi) / (2 * torch.pi) * 256).to(dtype=torch.uint8)


    return SLM_bit


def slm_screen_correct(slm_screen, fresnel_lens_screen, slm_correction, LUT):
    # slm_screen_f = np.mod(slm_screen + self.fresnel_lens_screen, 256)
    # slm_screen_f_corrected = np.mod(slm_screen_f + self.slm_correction, 256)
    # slm_screen_f_corrected_LUT = np.around(slm_screen_f_corrected*self.LUT/256).astype('uint8')
    
    # return slm_screen_f_corrected_LUT
    slm_screen_f = slm_screen + fresnel_lens_screen
    slm_screen_f_corrected = slm_screen_f + slm_correction
    slm_screen_f_corrected_LUT = torch.round(slm_screen_f_corrected * LUT).to(torch.uint8)
    slm_screen_f_corrected_LUT_cpu = slm_screen_f_corrected_LUT.clone().cpu().numpy()

    return slm_screen_f_corrected_LUT_cpu
